spring:
  datasource:
    url: jdbc:mysql://176.107.131.93:3306/diet
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lukasz1234
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true